name: helloapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.1
  camera: ^0.11.0+1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_ml_model_downloader: ^0.3.0+1
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  firebase_storage: ^12.0.1
  table_calendar: ^3.1.2
  intl: ^0.19.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loginimage.jpg
